### ISSUE TITLE
estimateMaxSystemMemory causes long running script warning

### ISSUE THREAD

**Issue by digitarald** [Mozilla-Games/browser_feature_test#1]
Just had this happen once on Nightly/OSX, linking to https://github.com/Mozilla-Games/browser_feature_test/blob/master/featuretest.js#L48

**Comment by juj** [comment]
Thanks, not quite sure about why that loop would be slow.. `numTriedAllocations` should be at most 96, and the inner loop should always take fixed 4 iterations, so at least the loop body execution couldn't shouldn't be high. Perhaps the issue has got something to do with allocating a lot of memory in typed arrays.

In any case, noticed that on Windows with Edge, having the console open so that asm.js optimizations are disabled, the CPU performance benchmark is extremely slow (100x slower), which would cause a hang there, so authored this commit to have a cutoff, and to make the overall test a bit faster: https://github.com/Mozilla-Games/browser_feature_test/commit/52073992d291fce0ce8ea10e603e190ce42cadea

**Comment by juj** [comment]
Observed behavior where the maximum system memory test would start swapping to disk, so removed that whole test, and only test for contiguous address space. https://github.com/Mozilla-Games/browser_feature_test/commit/771a1acdbcdc556fda7cdb7412d27efd81d0fcb4 . That closes this issue.
